version: '3.4'

networks:
  compass:
    driver: bridge

services:
  mongo:
    image: mongo:4.2
    networks:
      - compass
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER:-}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS:-}
    logging:
      driver: none
    command: mongod --port ${DB_PORT:-27017}

  app:
    build: .
    working_dir: /app/
    depends_on:
      - mongo
    networks:
      - compass
    ports:
      - ${PORT}:${PORT}
    command: npm run start
